export const screenSizeBreakPoint = 680;

export const SET_TOKEN = 'SET_TOKEN';
export const SET_CART = 'RETRIEVE_CART_DETAILS';
export const SET_PRODUCTS_ALL = 'SET_PRODUCTS_ALL_CHRONOLOGICAL_ORDER';
export const SET_PRODUCTS_SUBSET = 'SUBSET_PRODUCTS_ALL_CHRONOLOGICAL_ORDER';
export const CREATE_NEW_PRODUCT = 'CREATE_NEW_POST';
export const ADD_TO_CART = 'ADD_PRODUCT_TO_SHOPPING_CART';
export const REMOVE_FROM_CART = 'REMOVE_PRODUCT_FROM_SHOPPING_CART';
export const TOGGLE_CART_VIEW = 'TOGGLE_SHOW_NOT_SHOW_SHOPPING_CART';
export const NOT_LOGGED_IN = 'NOT_LOGGED_IN';
export const RESET_NOT_LOGGED_IN = 'RESET_NOT_LOGGED_IN';
export const GET_USER = 'GET_USER';
export const LOGOUT_UNSET_TOKEN = 'LOGOUT_UNSET_TOKEN';
export const SET_LOCATION_SUBSET = 'SET_LOCATION_SUBSET';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';


